version: "3.9"

networks:
  starterkit:
    external: true

volumes:
  mysql:

services:
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: "mysqladmin ping -h localhost --user=root --password=${MYSQL_ROOT_PASSWORD}"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 0s
    networks:
      - starterkit

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: ./nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    depends_on:
      wordpress:
        condition: service_started
    volumes:
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${NGINX_LOG_PATH}:/var/log/nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    restart: unless-stopped
    networks:
      - starterkit

  wordpress:
    container_name: ${COMPOSE_PROJECT_NAME}-wp
    build:
      context: ./wordpress
      args:
        - WP_VERSION=${WP_VERSION}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ${WP_SITE_ROOT_PATH}:/var/www/html
    ports:
      - ${WP_PORT}:80
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      VIRTUAL_PORT: ${WP_VIRTUAL_PORT}
      VIRTUAL_HOST: ${WP_VIRTUAL_HOST}
    user: ${USER_UID}:${USER_GID}
    extra_hosts:
      - "${WP_VIRTUAL_HOST}:${WP_EXTRA_HOST_IP}"
    networks:
      - starterkit
